######################################################################
#
# File name : test_post_synthesis_compile.do
# Created on: Wed Aug 19 20:54:52 +0800 2020
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
D:\\ModelSim\\win32pe\\vlib work
D:\\ModelSim\\win32pe\\vlib msim

D:\\ModelSim\\win32pe\\vlib msim/xil_defaultlib

D:\\ModelSim\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\ModelSim\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"test_post_synthesis_time_synth.v" \
"../../../../multicycleCPU54.srcs/sim_1/new/cpu_tb_post_synthesis.v" \


quit -force

