######################################################################
#
# File name : test_post_synthesis_simulate.do
# Created on: Wed Aug 19 20:55:10 +0800 2020
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vsim -voptargs="+acc" +transport_int_delays +pulse_r/0 +pulse_int_r/0 -L simprims_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.test_post_synthesis xil_defaultlib.glbl

do {test_post_synthesis_wave.do}

view wave
view structure
view signals

do {test_post_synthesis.udo}

run 1000ns
