######################################################################
#
# File name : test_post_synthesis_wave.do
# Created on: Wed Aug 19 20:55:10 +0800 2020
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
