# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/document/ComputerOrganizationDesign/CPU54/multicycleCPU54/multicycleCPU54.srcs/sources_1/ip/IMEM/IMEM.xci
# IP: The module: 'IMEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/document/ComputerOrganizationDesign/CPU54/multicycleCPU54/multicycleCPU54.srcs/sources_1/ip/IMEM/IMEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IMEM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: G:/document/ComputerOrganizationDesign/CPU54/multicycleCPU54/multicycleCPU54.srcs/sources_1/ip/IMEM/IMEM.xci
# IP: The module: 'IMEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/document/ComputerOrganizationDesign/CPU54/multicycleCPU54/multicycleCPU54.srcs/sources_1/ip/IMEM/IMEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IMEM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
