######################################################################
#
# File name : test_compile.do
# Created on: Fri Dec 18 18:28:20 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\ModelSim\\win32pe\\vlib work
D:\\ModelSim\\win32pe\\vlib msim

D:\\ModelSim\\win32pe\\vlib msim/xil_defaultlib

D:\\ModelSim\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\ModelSim\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../multicycleCPU54.srcs/sources_1/new/Asynchronous_D_FF.v" \
"../../../multicycleCPU54.srcs/sources_1/new/ADD.v" \
"../../../multicycleCPU54.srcs/sources_1/new/SRL.v" \
"../../../multicycleCPU54.srcs/sources_1/new/SLLSLR.v" \
"../../../multicycleCPU54.srcs/sources_1/new/SUBU.v" \
"../../../multicycleCPU54.srcs/sources_1/new/LUI.v" \
"../../../multicycleCPU54.srcs/sources_1/new/SRA.v" \
"../../../multicycleCPU54.srcs/sources_1/new/NOR.v" \
"../../../multicycleCPU54.srcs/sources_1/new/XOR.v" \
"../../../multicycleCPU54.srcs/sources_1/new/complement.v" \
"../../../multicycleCPU54.srcs/sources_1/new/AND.v" \
"../../../multicycleCPU54.srcs/sources_1/new/pcreg.v" \
"../../../multicycleCPU54.srcs/sources_1/new/SLTU.v" \
"../../../multicycleCPU54.srcs/sources_1/new/SUB.v" \
"../../../multicycleCPU54.srcs/sources_1/new/OR.v" \
"../../../multicycleCPU54.srcs/sources_1/new/selector.v" \
"../../../multicycleCPU54.srcs/sources_1/new/ADDU.v" \
"../../../multicycleCPU54.srcs/sources_1/new/divu.v" \
"../../../multicycleCPU54.srcs/sources_1/new/SLT.v" \
"../../../multicycleCPU54.srcs/sources_1/new/multu.v" \
"../../../multicycleCPU54.srcs/sources_1/new/alu.v" \
"../../../multicycleCPU54.srcs/sources_1/new/div.v" \
"../../../multicycleCPU54.srcs/sources_1/new/npc.v" \
"../../../multicycleCPU54.srcs/sources_1/new/mux.v" \
"../../../multicycleCPU54.srcs/sources_1/new/regfile.v" \
"../../../multicycleCPU54.srcs/sources_1/new/mult.v" \
"../../../multicycleCPU54.srcs/sources_1/new/clz.v" \
"../../../multicycleCPU54.srcs/sources_1/new/save.v" \
"../../../multicycleCPU54.srcs/sources_1/new/cu.v" \
"../../../multicycleCPU54.srcs/sources_1/new/extend.v" \
"../../../multicycleCPU54.srcs/sources_1/new/cp0.v" \
"../../../multicycleCPU54.srcs/sources_1/new/z.v" \
"../../../multicycleCPU54.srcs/sources_1/new/II.v" \
"../../../multicycleCPU54.srcs/sources_1/new/cpmem.v" \
"../../../multicycleCPU54.srcs/sources_1/new/decoder.v" \
"../../../multicycleCPU54.srcs/sources_1/new/memory.v" \
"../../../multicycleCPU54.srcs/sources_1/new/cpu.v" \
"../../../multicycleCPU54.srcs/sources_1/new/sccomp_dataflow.v" \
"../../../multicycleCPU54.srcs/sim_1/new/cpu_tb.v" \


# compile glbl module
D:\\ModelSim\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

