######################################################################
#
# File name : test_simulate.do
# Created on: Fri Dec 18 18:28:33 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.test xil_defaultlib.glbl

do {test_wave.do}

view wave
view structure
view signals

do {test.udo}

run 1000ns
