######################################################################
#
# File name : test_wave.do
# Created on: Fri Dec 18 18:28:33 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
